# Generated by Django 6.1 on 2026-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('closed', 'Closed'), ('reopen', 'Reopen')], default='open', max_length=20),
        ),
    ]
