# Generated by Django 6.1 on 2026-08-10 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_project', 'Created a project'), ('update_project', 'Updated a project'), ('delete_project', 'Deleted a project'), ('create_task', 'Created a task'), ('update_task', 'Updated a task'), ('delete_task', 'Deleted a task'), ('complete_task', 'Completed a task'), ('add_comment', 'Added a comment'), ('add_team_member', 'Added a team member')], max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx'), models.Index(fields=['user', '-created_at'], name='activity_ac_user_id_9aae35_idx')],
            },
        ),
    ]
