# Generated by Django 6.1 on 2026-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create_project', 'Created a project'), ('update_project', 'Updated a project'), ('delete_project', 'Deleted a project'), ('create_task', 'Created a task'), ('update_task', 'Updated a task'), ('delete_task', 'Deleted a task'), ('complete_task', 'Completed a task'), ('add_comment', 'Added a comment'), ('add_team_member', 'Added a team member'), ('assign_task', 'Assigned a task'), ('change_status', 'Changed task status'), ('remove_team_member', 'Removed a team member'), ('change_role', 'Changed member role'), ('mention_user', 'Mentioned a user')], max_length=30),
        ),
    ]
